### PR TITLE
build(added post-title block): added functionality for post-title block

### PR DESCRIPTION
**Pull request by Danishkhurshid**

### CODE REVIEW

**Comment by Danishkhurshid** [comment]
@bmarshall511 Please review.
1. Added post title plugin integration
2. Dynamically display post titles within the query loop using title and title component
3. Added a setting to render post title as a link.
4. Tested and verified styling options on WordPress
ss
ss2

**Comment by Danishkhurshid** [comment]
@bmarshall511 updated the PR. Please check.

**Comment by bmarshall511** [comment]
@Danishkhurshid Not seeing the post title share the code you created

**Comment by bmarshall511** [comment]
@Danishkhurshid My bad, missed it. Looks great!

**Pull request merged**
